props:
  bitBucketUrl : http://localhost
  bitBucketUser : root
  bitBucketPassword : root

  cachePath: /tmp/testdb
  cacheName: bitbucket
  cacheExpiration: 7200

  repositoryPath: /home/cornel/prAct